const std = @import("std");

const assert = std.debug.assert;
const log = std.log;
const FRNG = @This();

entropy: []const u8,

pub const Error = error{OutOfEntropy};

pub fn bytes(frng: *FRNG, size: usize) Error![]const u8 {
    if (frng.entropy.len < size) return error.OutOfEntropy;
    const result = frng.entropy[0..size];
    frng.entropy = frng.entropy[size..];
    return result;
}

pub fn array(frng: *FRNG, comptime size: usize) Error![size]u8 {
    return (try frng.bytes(size))[0..size].*;
}

pub fn int(frng: *FRNG, Int: type) Error!Int {
    comptime assert(@typeInfo(Int).int.signedness == .unsigned);
    comptime assert(@import("builtin").cpu.arch.endian() == .little);
    return @bitCast(try frng.array(@sizeOf(Int)));
}

pub fn boolean(frng: *FRNG) Error!bool {
    return (try frng.int(u8)) & 1 == 1;
}

pub fn intInclusive(frng: *FRNG, Int: type, max: Int) Error!Int {
    comptime assert(@typeInfo(Int).int.signedness == .unsigned);
    if (max == std.math.maxInt(Int)) return try frng.int(Int);

    const bits = @typeInfo(Int).int.bits;
    const less_than = max + 1;

    var x = try frng.int(Int);
    var m = std.math.mulWide(Int, x, less_than);
    var l: Int = @truncate(m);
    if (l < less_than) {
        var t = -%less_than;

        if (t >= less_than) {
            t -= less_than;
            if (t >= less_than) t %= less_than;
        }
        while (l < t) {
            x = try frng.int(Int);
            m = std.math.mulWide(Int, x, less_than);
            l = @truncate(m);
        }
    }
    return @intCast(m >> bits);
}

pub fn rangeInclusive(frng: *FRNG, Int: type, min: Int, max: Int) Error!Int {
    comptime assert(@typeInfo(Int).int.signedness == .unsigned);
    assert(min <= max);
    return min + try frng.intInclusive(Int, max - min);
}

pub fn index(frng: *FRNG, slice: anytype) Error!usize {
    assert(slice.len > 0);
    return try frng.rangeInclusive(usize, 0, slice.len - 1);
}

pub fn randomWeights(frng: *FRNG, Weights: type) Error!Weights {
    var result: Weights = undefined;
    inline for (comptime std.meta.fieldNames(Weights)) |field| {
        @field(result, field) = try frng.rangeInclusive(u32, 1, 100);
    }
    return result;
}

pub fn weighted(frng: *FRNG, weights: anytype) Error!std.meta.FieldEnum(@TypeOf(weights)) {
    const fields = comptime std.meta.fieldNames(@TypeOf(weights));

    var total: u32 = 0;
    inline for (fields) |field| total += @field(weights, field);
    assert(total > 0);

    // Draw from the narrowest integer that can hold the total rather than always spending eight
    // bytes on a u64. Weight totals are small in practice, and a weighted draw per generated byte
    // otherwise dominates the entropy budget.
    const u8_max = std.math.maxInt(u8);
    const u16_max = std.math.maxInt(u16);
    var pick: u32 = switch (total) {
        0 => unreachable,
        1...u8_max + 1 => try frng.intInclusive(u8, @intCast(total - 1)),
        u8_max + 2...u16_max + 1 => try frng.intInclusive(u16, @intCast(total - 1)),
        else => try frng.intInclusive(u32, total - 1),
    };
    inline for (fields) |field| {
        const weight = @field(weights, field);
        if (pick < weight) {
            return @field(
                std.meta.FieldEnum(@TypeOf(weights)),
                field,
            );
        }
        pick -= weight;
    }
    unreachable;
}

const Driver = struct {
    io: std.Io,
    sut: []const u8,
    buffer: []u8,

    // TODO: Rewrite this. Difficult to read. `pass` should track the inverse and be called
    // `found_fail`. Refactor to get rid of the `_next` suffixes.
    fn search(driver: Driver, options: struct {
        attempts: u32 = 100,
    }) !union(enum) { pass, fail: struct { size: u32, seed: u64 } } {
        var found_size: ?u32 = null;
        var found_seed: ?u64 = null;

        var pass: bool = true;
        var size: u32 = 16;
        var step: u32 = 16;
        for (0..1024) |_| {
            if (step == 0 or size == 0) break;
            const size_next = if (pass) size + step else size -| step;
            if (size_next > driver.buffer.len) break;

            const outcome = try driver.runMultiple(.{
                .size = size_next,
                .attempts = options.attempts,
            });
            switch (outcome) {
                .pass => log.info("pass: size={}", .{size_next}),
                .fail => |seed| {
                    found_size = size_next;
                    found_seed = seed;
                    log.err("fail: size={} seed={}", .{ size_next, seed });
                },
            }
            const pass_next = (outcome == .pass);

            if (pass and pass_next) {
                step *= 2;
            } else if (!pass and !pass_next) {
                // Keep the step.
            } else {
                step /= 2;
            }

            if (pass or !pass_next) {
                size = size_next;
                pass = pass_next;
            }
        } else @panic("safety counter");

        if (found_size == null) return .pass;
        return .{ .fail = .{
            .size = found_size.?,
            .seed = found_seed.?,
        } };
    }

    fn runMultiple(driver: Driver, options: struct {
        size: u32,
        attempts: u32,
    }) !union(enum) { pass, fail: u64 } {
        assert(options.size <= driver.buffer.len);

        for (0..options.attempts) |_| {
            var seed: u64 = undefined;
            driver.io.random(@ptrCast(&seed));

            switch (try driver.runOnce(.{
                .seed = seed,
                .size = options.size,
                .quiet = true,
            })) {
                .fail => return .{ .fail = seed },
                .pass => {},
            }
        }
        return .pass;
    }

    fn runOnce(driver: Driver, options: struct {
        size: u32,
        seed: u64,
        quiet: bool,
    }) !enum { pass, fail } {
        assert(options.size <= driver.buffer.len);
        const entropy = driver.buffer[0..options.size];

        var child = try std.process.spawn(driver.io, .{
            .argv = &.{driver.sut},
            .stdin = .pipe,
            .stderr = if (options.quiet) .ignore else .inherit,
        });

        var rng: std.Random.DefaultPrng = .init(options.seed);
        rng.random().bytes(entropy);

        try child.stdin.?.writeStreamingAll(driver.io, entropy);
        child.stdin.?.close(driver.io);
        child.stdin = null;

        const term = try child.wait(driver.io);
        return if (term == .exited and term.exited == 0) .pass else .fail;
    }
};

pub fn main(init: std.process.Init) !u8 {
    const allocator = init.gpa;
    const io = init.io;

    var args = std.process.Args.Iterator.init(init.minimal.args);
    assert(args.skip()); // first arg is executable path
    const sut = args.next() orelse @panic("missing file path arg");
    const mode: union(enum) {
        replay: struct { size: u32, seed: u64 },
        search: struct { attempts: u32, size_max: u32 },
    } = blk: {
        const arg = args.next() orelse @panic("missing mode arg");
        const replay_prefix = "--replay="; // --replay={size}:{seed}
        const search_prefix = "--search="; // --search={attempts}:{size_max}
        const colon_index = std.mem.indexOfScalar(u8, arg, ':') orelse @panic("invalid arg");

        if (std.mem.startsWith(u8, arg, search_prefix)) break :blk .{
            .search = .{
                .attempts = try std.fmt.parseInt(u32, arg[search_prefix.len..colon_index], 10),
                .size_max = try std.fmt.parseInt(u32, arg[colon_index + 1 ..], 10),
            },
        } else if (std.mem.startsWith(u8, arg, replay_prefix)) break :blk .{
            .replay = .{
                .size = try std.fmt.parseInt(u32, arg[replay_prefix.len..colon_index], 10),
                .seed = try std.fmt.parseInt(u64, arg[colon_index + 1 ..], 10),
            },
        } else @panic("unrecognised arg");
    };

    const size_max = switch (mode) {
        .replay => |options| options.size,
        .search => |options| options.size_max,
    };

    const buffer = try allocator.alloc(u8, size_max);
    defer allocator.free(buffer);

    var driver: Driver = .{
        .io = io,
        .buffer = buffer,
        .sut = sut,
    };

    switch (mode) {
        .replay => |options| _ = try driver.runOnce(.{
            .size = options.size,
            .seed = options.seed,
            .quiet = false,
        }),
        .search => |options| switch (try driver.search(.{ .attempts = options.attempts })) {
            .pass => log.info("ok", .{}),
            .fail => |fail| {
                log.err(
                    "minimized failure (size={}, seed={}) printed the following to stderr",
                    .{ fail.size, fail.seed },
                );
                // Replay the minimised seed verbosely.
                _ = try driver.runOnce(.{
                    .size = fail.size,
                    .seed = fail.seed,
                    .quiet = false,
                });
                log.err(
                    "replay with:\n\tzig build fuzz -- --replay={}:{}",
                    .{ fail.size, fail.seed },
                );
                return 1;
            },
        },
    }

    return 0;
}
